//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1214064_rangees_de_sieges_de_cinema_sur_noir_gratuit_vectoriel {
            get {
                object obj = ResourceManager.GetObject("1214064-rangees-de-sieges-de-cinema-sur-noir-gratuit-vectoriel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1214064_rangees_de_sieges_de_cinema_sur_noir_gratuit_vectoriel1 {
            get {
                object obj = ResourceManager.GetObject("1214064-rangees-de-sieges-de-cinema-sur-noir-gratuit-vectoriel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1214064_rangees_de_sieges_de_cinema_sur_noir_gratuit_vectoriel2 {
            get {
                object obj = ResourceManager.GetObject("1214064-rangees-de-sieges-de-cinema-sur-noir-gratuit-vectoriel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1214064_rangees_de_sieges_de_cinema_sur_noir_gratuit_vectoriel3 {
            get {
                object obj = ResourceManager.GetObject("1214064-rangees-de-sieges-de-cinema-sur-noir-gratuit-vectoriel3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1214064_rangees_de_sieges_de_cinema_sur_noir_gratuit_vectoriel4 {
            get {
                object obj = ResourceManager.GetObject("1214064-rangees-de-sieges-de-cinema-sur-noir-gratuit-vectoriel4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_507677881_lwsOUToBTTOk0mHHPhyudfK4BGS9LGO1__2_ {
            get {
                object obj = ResourceManager.GetObject("360_F_507677881_lwsOUToBTTOk0mHHPhyudfK4BGS9LGO1 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_507677881_lwsOUToBTTOk0mHHPhyudfK4BGS9LGO1__2_1 {
            get {
                object obj = ResourceManager.GetObject("360_F_507677881_lwsOUToBTTOk0mHHPhyudfK4BGS9LGO1 (2)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ab13_16671665709974_1920 {
            get {
                object obj = ResourceManager.GetObject("4ab13-16671665709974-1920", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4ab13_16671665709974_19201 {
            get {
                object obj = ResourceManager.GetObject("4ab13-16671665709974-19201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _72714049 {
            get {
                object obj = ResourceManager.GetObject("72714049", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _90a27ba9be0db70843efbf48fa988d5c {
            get {
                object obj = ResourceManager.GetObject("90a27ba9be0db70843efbf48fa988d5c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _90a27ba9be0db70843efbf48fa988d5c__2_ {
            get {
                object obj = ResourceManager.GetObject("90a27ba9be0db70843efbf48fa988d5c (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c454d3e7e714d54dc292a61d3b2dfc96__2_ {
            get {
                object obj = ResourceManager.GetObject("c454d3e7e714d54dc292a61d3b2dfc96 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cinema_background_concept_movie_theater_object_isolated_on_white_background_illustration_free_vector {
            get {
                object obj = ResourceManager.GetObject("cinema-background-concept-movie-theater-object-isolated-on-white-background-illus" +
                        "tration-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cinema_background_concept_movie_theater_object_isolated_on_white_background_illustration_free_vector1 {
            get {
                object obj = ResourceManager.GetObject("cinema-background-concept-movie-theater-object-isolated-on-white-background-illus" +
                        "tration-free-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_wallpaper_cinema_high_quality_cinema {
            get {
                object obj = ResourceManager.GetObject("desktop-wallpaper-cinema-high-quality-cinema", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_wallpaper_cinema_high_quality_cinema1 {
            get {
                object obj = ResourceManager.GetObject("desktop-wallpaper-cinema-high-quality-cinema1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_wallpaper_cinema_high_quality_cinema2 {
            get {
                object obj = ResourceManager.GetObject("desktop-wallpaper-cinema-high-quality-cinema2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_wallpaper_cinema_high_quality_cinema3 {
            get {
                object obj = ResourceManager.GetObject("desktop-wallpaper-cinema-high-quality-cinema3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_pixabay_531880 {
            get {
                object obj = ResourceManager.GetObject("pexels-pixabay-531880", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_black_background_with_popcorn_image_2652581 {
            get {
                object obj = ResourceManager.GetObject("pngtree-black-background-with-popcorn-image_2652581", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
